### PR TITLE
Make optional params settable

### PR DESCRIPTION
**Pull request by jlg4**
Some optional parameters are needs to be set

### CODE REVIEW

**Review by CrahunGit — APPROVED** [review]

**Comment by CrahunGit** [comment]
Perfect. Thank you very much for your effort!

**Comment by jlg4** [comment]
Thanks! And thanks for the library, super helpful!

**Comment by jlg4** [comment]
Would you be able to create a new nuget release with the changes? Im currently using reflection to set the parameter.

Thanks!

**Comment by CrahunGit** [comment]
Sorry, I was out of time. It will be available this morning!

**Comment by CrahunGit** [comment]
All right, Version 3.1.0 with your changes is on nuget. Thank you!

**Pull request merged**
